DELETE FROM skills;

INSERT INTO skills (name, category, level, display_order) VALUES
('Java', 'Programming', 'PRIMARY', 1),
('JavaScript', 'Programming', 'STRONG', 2),
('C++', 'Programming', 'WORKING_KNOWLEDGE', 3),
('C#', 'Programming', 'WORKING_KNOWLEDGE', 4),
('SQL', 'Programming', 'STRONG', 5),
('Spring Boot', 'Backend', 'PRIMARY', 6),
('Spring Security', 'Backend', 'STRONG', 7),
('Spring MVC', 'Backend', 'STRONG', 8),
('Hibernate / JPA', 'Backend', 'STRONG', 9),
('Node.js', 'Backend', 'STRONG', 10),
('Express.js', 'Backend', 'STRONG', 11),
('REST API Design', 'Backend', 'PRIMARY', 12),
('Microservices', 'Backend', 'WORKING_KNOWLEDGE', 13),
('JWT Authentication', 'Backend', 'STRONG', 14),
('React.js', 'Frontend', 'PRIMARY', 15),
('Redux Toolkit', 'Frontend', 'STRONG', 16),
('React Router', 'Frontend', 'STRONG', 17),
('Tailwind CSS', 'Frontend', 'STRONG', 18),
('HTML5 / CSS3', 'Frontend', 'STRONG', 19),
('Bootstrap', 'Frontend', 'WORKING_KNOWLEDGE', 20),
('MySQL', 'Database', 'PRIMARY', 21),
('Oracle SQL / PL-SQL', 'Database', 'STRONG', 22),
('MongoDB', 'Database', 'STRONG', 23),
('Docker', 'Cloud, DevOps & Tools', 'STRONG', 24),
('Kubernetes', 'Cloud, DevOps & Tools', 'WORKING_KNOWLEDGE', 25),
('Jenkins', 'Cloud, DevOps & Tools', 'WORKING_KNOWLEDGE', 26),
('Microsoft Azure', 'Cloud, DevOps & Tools', 'WORKING_KNOWLEDGE', 27),
('Git & GitHub', 'Cloud, DevOps & Tools', 'PRIMARY', 28),
('Postman / Swagger', 'Cloud, DevOps & Tools', 'STRONG', 29),
('Maven', 'Cloud, DevOps & Tools', 'STRONG', 30),
('JUnit / Mockito', 'Testing & QA', 'WORKING_KNOWLEDGE', 31),
('Selenium WebDriver', 'Testing & QA', 'WORKING_KNOWLEDGE', 32),
('Data Structures & Algorithms', 'Computer Science', 'STRONG', 33),
('Object-Oriented Programming', 'Computer Science', 'PRIMARY', 34),
('DBMS', 'Computer Science', 'STRONG', 35),
('Operating Systems', 'Computer Science', 'WORKING_KNOWLEDGE', 36),
('Computer Networks', 'Computer Science', 'WORKING_KNOWLEDGE', 37);